config/routes.rb
Mytestproj::Application.routes.draw do
  
  resources :homes
  resources :restaurants

   root 'homes#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :name,
      [:name, :city],
      [:name, :street, :city],
      [:name, :street_number, :street, :city]
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
   def index
     @restaurants = Restaurant.all
   end

   def new
     @restaurant = Restaurant.new
   end

   def create
     @restaurant = Restaurant.new(restaurant_params)
     if @restaurant.save
       redirect_to homes_path
     else
      render :action => "new"
     end
   end

  def show
    @restaurant = Restaurant.friendly.find(params[:id])
  end

   private
   def restaurant_params
      params.require(:restaurant).permit!
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/homes/index.html.erb
<h2>Welcome To my home page</h2>

<%= link_to "restaurants", restaurants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mytestproj</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<p>This is index page</p>
<%= link_to "new", new_restaurant_path %>

<br/>

<table border="1">
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Street</th>
    <th>Street Number</th>
    <th>Status</th>
  </tr>
  <% @restaurants.each do |r| %>
    <td>
     <%= r.name %>
    </td>
    <td>
     <%= r.city %>
    </td>
    <td>
     <%= r.street %>
    </td>
    <td>
     <%= r.street_number %>
    </td>
    <td>
     <%= link_to "show", restaurant_path(r.friendly_id) %>
    </td>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
  Name: <%= f.text_field :name %> <br/>
  City: <%= f.text_field :city %> <br/> 
  Street:  <%= f.text_field :street %> <br/>
  Street Number:  <%= f.text_field :street_number %> <br/>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<%= @restaurant.id %> <br/>
<%= @restaurant.name %> <br/>
<%= @restaurant.city %> <br/>
<%= @restaurant.street %> <br/>
<%= @restaurant.street_number %> <br/>